stages:
  - docker
  - latest

variables:
  REGISTRY_IMAGE: "vondruska/llnode"
  LATEST_NODE: "12"
  
.docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker build --pull -t "$REGISTRY_IMAGE:$NODE_VERSION" --build-arg NODE_VERSION .
    - docker push "$REGISTRY_IMAGE"
  only:
    - master

node8:
  extends: .docker_build
  variables:
    NODE_VERSION: "8"

node10:
  extends: .docker_build
  variables:
    NODE_VERSION: "10"

node12:
  extends: .docker_build
  variables:
    NODE_VERSION: "12"

latest:
  stage: latest
  image: docker
  services:
    - docker:dind
  before_script:
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
  script:
    - docker pull "$REGISTRY_IMAGE:$LATEST_NODE"
    - docker tag "$REGISTRY_IMAGE:$LATEST_NODE" "$REGISTRY_IMAGE:latest"
    - docker push "$REGISTRY_IMAGE"
  only:
    - master