name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: vondruska/llnode
      LATEST: 12

    strategy:
      matrix:
        node: [8, 10, 12]
  
    steps:
    - uses: actions/checkout@v1
    
    - name: Docker login
      env:
        REGISTRY_USER: ${{secrets.REGISTRY_USER}}
        REGISTRY_PASSWORD: ${{secrets.REGISTRY_PASSWORD}}
      run: docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASSWORD" 
    

    - name: Build docker image
      env:
        NODE_VERSION: ${{ matrix.node }}
      run:  docker build --pull -t "$IMAGE_NAME:$NODE_VERSION" --build-arg NODE_VERSION .

    - name: Tag latest
      if: env.LATEST == matrix.node
      env:
        NODE_VERSION: ${{ matrix.node }}
      run: docker tag "$IMAGE_NAME:$NODE_VERSION" "$IMAGE_NAME:latest"

    - name: Push images
      run: docker push $IMAGE_NAME
